
export const LOGIN_SUCCESSFUL = "LOGIN SUCCESSFUL"
export const LOGIN_FAIL = "LOGIN FAIL"
export const LOGIN_LOADING = "LOGIN LOADING"

export const REGISTER_SUCCESSFUL = "REGISTER SUCCESSFUL"
export const REGISTER_FAIL = "REGISTER FAIL"
export const REGISTER_LOADING = "REGISTER LOADING"

export const GET_CONTACTS_SUCCESSFUL = "GET CONTACTS SUCCESSFUL"
export const GET_CONTACTS_FAIL = "GET CONTACTS FAIL"
export const GET_CONTACTS_LOADING = "GET CONTACTS LOADING"

export const CREATE_CONTACT_SUCCESSFUL = "CREATE CONTACT SUCCESSFUL"
export const CREATE_CONTACT_FAIL = "CREATE CONTACT FAIL"
export const CREATE_CONTACT_LOADING = "CREATE CONTACT LOADING"

export const EDIT_CONTACT_SUCCESSFUL = "EDIT CONTACT SUCCESSFUL"
export const EDIT_CONTACT_FAIL = "EDIT CONTACT FAIL"
export const EDIT_CONTACT_LOADING = "EDIT CONTACT LOADING"


export const CLEAR_AUTH_STATE = "CLEAR AUTH STATE"
export const LOGOUT = "LOGOUT"